/*
Warm up

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/



//
// while (x <= 89) {
//   z = x + y
//   x++
//   console.log(z);
// }


// let x, y, z
//
// x = 0
// y = 1
//
//
//
// for (x = 0; x <= 89; x++) {
//   z = x + y
//   x = y
//   y = z
//   console.log(z);
// }
//
//
var evenSum = 2
var sum = 0
var i;
var fib = [];

fib[0] = 0;
fib[1] = 1;
for (i=2; i<=10; i++)
{
  fib[i] = fib[i-2] + fib[i-1];
  if (i % 2 === 0) {
    sum += evenSum;
    console.log(sum);
  }

  // console.log(fib[i]);
}
